# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/3ds_dev/PlaiSysUpdater

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/3ds_dev/PlaiSysUpdater

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/3ds_dev/PlaiSysUpdater/CMakeFiles /home/dev/3ds_dev/PlaiSysUpdater/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/3ds_dev/PlaiSysUpdater/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PlaiSysUpdater

# Build rule for target.
PlaiSysUpdater: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PlaiSysUpdater
.PHONY : PlaiSysUpdater

# fast build rule for target.
PlaiSysUpdater/fast:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/build
.PHONY : PlaiSysUpdater/fast

#=============================================================================
# Target rules for targets named PlaiSysUpdater_3dsx

# Build rule for target.
PlaiSysUpdater_3dsx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PlaiSysUpdater_3dsx
.PHONY : PlaiSysUpdater_3dsx

# fast build rule for target.
PlaiSysUpdater_3dsx/fast:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater_3dsx.dir/build.make CMakeFiles/PlaiSysUpdater_3dsx.dir/build
.PHONY : PlaiSysUpdater_3dsx/fast

#=============================================================================
# Target rules for targets named PlaiSysUpdater_Citra

# Build rule for target.
PlaiSysUpdater_Citra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PlaiSysUpdater_Citra
.PHONY : PlaiSysUpdater_Citra

# fast build rule for target.
PlaiSysUpdater_Citra/fast:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater_Citra.dir/build.make CMakeFiles/PlaiSysUpdater_Citra.dir/build
.PHONY : PlaiSysUpdater_Citra/fast

#=============================================================================
# Target rules for targets named PlaiSysUpdater_3dslink

# Build rule for target.
PlaiSysUpdater_3dslink: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PlaiSysUpdater_3dslink
.PHONY : PlaiSysUpdater_3dslink

# fast build rule for target.
PlaiSysUpdater_3dslink/fast:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater_3dslink.dir/build.make CMakeFiles/PlaiSysUpdater_3dslink.dir/build
.PHONY : PlaiSysUpdater_3dslink/fast

#=============================================================================
# Target rules for targets named PlaiSysUpdater_Cia

# Build rule for target.
PlaiSysUpdater_Cia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PlaiSysUpdater_Cia
.PHONY : PlaiSysUpdater_Cia

# fast build rule for target.
PlaiSysUpdater_Cia/fast:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater_Cia.dir/build.make CMakeFiles/PlaiSysUpdater_Cia.dir/build
.PHONY : PlaiSysUpdater_Cia/fast

source/Debug.obj: source/Debug.cpp.obj

.PHONY : source/Debug.obj

# target to build an object file
source/Debug.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Debug.cpp.obj
.PHONY : source/Debug.cpp.obj

source/Debug.i: source/Debug.cpp.i

.PHONY : source/Debug.i

# target to preprocess a source file
source/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Debug.cpp.i
.PHONY : source/Debug.cpp.i

source/Debug.s: source/Debug.cpp.s

.PHONY : source/Debug.s

# target to generate assembly for a file
source/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Debug.cpp.s
.PHONY : source/Debug.cpp.s

source/Main.obj: source/Main.cpp.obj

.PHONY : source/Main.obj

# target to build an object file
source/Main.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Main.cpp.obj
.PHONY : source/Main.cpp.obj

source/Main.i: source/Main.cpp.i

.PHONY : source/Main.i

# target to preprocess a source file
source/Main.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Main.cpp.i
.PHONY : source/Main.cpp.i

source/Main.s: source/Main.cpp.s

.PHONY : source/Main.s

# target to generate assembly for a file
source/Main.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Main.cpp.s
.PHONY : source/Main.cpp.s

source/SuperUserLib3DS/libsu.obj: source/SuperUserLib3DS/libsu.c.obj

.PHONY : source/SuperUserLib3DS/libsu.obj

# target to build an object file
source/SuperUserLib3DS/libsu.c.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/SuperUserLib3DS/libsu.c.obj
.PHONY : source/SuperUserLib3DS/libsu.c.obj

source/SuperUserLib3DS/libsu.i: source/SuperUserLib3DS/libsu.c.i

.PHONY : source/SuperUserLib3DS/libsu.i

# target to preprocess a source file
source/SuperUserLib3DS/libsu.c.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/SuperUserLib3DS/libsu.c.i
.PHONY : source/SuperUserLib3DS/libsu.c.i

source/SuperUserLib3DS/libsu.s: source/SuperUserLib3DS/libsu.c.s

.PHONY : source/SuperUserLib3DS/libsu.s

# target to generate assembly for a file
source/SuperUserLib3DS/libsu.c.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/SuperUserLib3DS/libsu.c.s
.PHONY : source/SuperUserLib3DS/libsu.c.s

source/Updates/UpdateInfoEur-2-1.obj: source/Updates/UpdateInfoEur-2-1.cpp.obj

.PHONY : source/Updates/UpdateInfoEur-2-1.obj

# target to build an object file
source/Updates/UpdateInfoEur-2-1.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoEur-2-1.cpp.obj
.PHONY : source/Updates/UpdateInfoEur-2-1.cpp.obj

source/Updates/UpdateInfoEur-2-1.i: source/Updates/UpdateInfoEur-2-1.cpp.i

.PHONY : source/Updates/UpdateInfoEur-2-1.i

# target to preprocess a source file
source/Updates/UpdateInfoEur-2-1.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoEur-2-1.cpp.i
.PHONY : source/Updates/UpdateInfoEur-2-1.cpp.i

source/Updates/UpdateInfoEur-2-1.s: source/Updates/UpdateInfoEur-2-1.cpp.s

.PHONY : source/Updates/UpdateInfoEur-2-1.s

# target to generate assembly for a file
source/Updates/UpdateInfoEur-2-1.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoEur-2-1.cpp.s
.PHONY : source/Updates/UpdateInfoEur-2-1.cpp.s

source/Updates/UpdateInfoEur.obj: source/Updates/UpdateInfoEur.cpp.obj

.PHONY : source/Updates/UpdateInfoEur.obj

# target to build an object file
source/Updates/UpdateInfoEur.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoEur.cpp.obj
.PHONY : source/Updates/UpdateInfoEur.cpp.obj

source/Updates/UpdateInfoEur.i: source/Updates/UpdateInfoEur.cpp.i

.PHONY : source/Updates/UpdateInfoEur.i

# target to preprocess a source file
source/Updates/UpdateInfoEur.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoEur.cpp.i
.PHONY : source/Updates/UpdateInfoEur.cpp.i

source/Updates/UpdateInfoEur.s: source/Updates/UpdateInfoEur.cpp.s

.PHONY : source/Updates/UpdateInfoEur.s

# target to generate assembly for a file
source/Updates/UpdateInfoEur.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoEur.cpp.s
.PHONY : source/Updates/UpdateInfoEur.cpp.s

source/Updates/UpdateInfoJpn-2-1.obj: source/Updates/UpdateInfoJpn-2-1.cpp.obj

.PHONY : source/Updates/UpdateInfoJpn-2-1.obj

# target to build an object file
source/Updates/UpdateInfoJpn-2-1.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoJpn-2-1.cpp.obj
.PHONY : source/Updates/UpdateInfoJpn-2-1.cpp.obj

source/Updates/UpdateInfoJpn-2-1.i: source/Updates/UpdateInfoJpn-2-1.cpp.i

.PHONY : source/Updates/UpdateInfoJpn-2-1.i

# target to preprocess a source file
source/Updates/UpdateInfoJpn-2-1.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoJpn-2-1.cpp.i
.PHONY : source/Updates/UpdateInfoJpn-2-1.cpp.i

source/Updates/UpdateInfoJpn-2-1.s: source/Updates/UpdateInfoJpn-2-1.cpp.s

.PHONY : source/Updates/UpdateInfoJpn-2-1.s

# target to generate assembly for a file
source/Updates/UpdateInfoJpn-2-1.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoJpn-2-1.cpp.s
.PHONY : source/Updates/UpdateInfoJpn-2-1.cpp.s

source/Updates/UpdateInfoJpn.obj: source/Updates/UpdateInfoJpn.cpp.obj

.PHONY : source/Updates/UpdateInfoJpn.obj

# target to build an object file
source/Updates/UpdateInfoJpn.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoJpn.cpp.obj
.PHONY : source/Updates/UpdateInfoJpn.cpp.obj

source/Updates/UpdateInfoJpn.i: source/Updates/UpdateInfoJpn.cpp.i

.PHONY : source/Updates/UpdateInfoJpn.i

# target to preprocess a source file
source/Updates/UpdateInfoJpn.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoJpn.cpp.i
.PHONY : source/Updates/UpdateInfoJpn.cpp.i

source/Updates/UpdateInfoJpn.s: source/Updates/UpdateInfoJpn.cpp.s

.PHONY : source/Updates/UpdateInfoJpn.s

# target to generate assembly for a file
source/Updates/UpdateInfoJpn.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoJpn.cpp.s
.PHONY : source/Updates/UpdateInfoJpn.cpp.s

source/Updates/UpdateInfoUsa-2-1.obj: source/Updates/UpdateInfoUsa-2-1.cpp.obj

.PHONY : source/Updates/UpdateInfoUsa-2-1.obj

# target to build an object file
source/Updates/UpdateInfoUsa-2-1.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoUsa-2-1.cpp.obj
.PHONY : source/Updates/UpdateInfoUsa-2-1.cpp.obj

source/Updates/UpdateInfoUsa-2-1.i: source/Updates/UpdateInfoUsa-2-1.cpp.i

.PHONY : source/Updates/UpdateInfoUsa-2-1.i

# target to preprocess a source file
source/Updates/UpdateInfoUsa-2-1.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoUsa-2-1.cpp.i
.PHONY : source/Updates/UpdateInfoUsa-2-1.cpp.i

source/Updates/UpdateInfoUsa-2-1.s: source/Updates/UpdateInfoUsa-2-1.cpp.s

.PHONY : source/Updates/UpdateInfoUsa-2-1.s

# target to generate assembly for a file
source/Updates/UpdateInfoUsa-2-1.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoUsa-2-1.cpp.s
.PHONY : source/Updates/UpdateInfoUsa-2-1.cpp.s

source/Updates/UpdateInfoUsa.obj: source/Updates/UpdateInfoUsa.cpp.obj

.PHONY : source/Updates/UpdateInfoUsa.obj

# target to build an object file
source/Updates/UpdateInfoUsa.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoUsa.cpp.obj
.PHONY : source/Updates/UpdateInfoUsa.cpp.obj

source/Updates/UpdateInfoUsa.i: source/Updates/UpdateInfoUsa.cpp.i

.PHONY : source/Updates/UpdateInfoUsa.i

# target to preprocess a source file
source/Updates/UpdateInfoUsa.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoUsa.cpp.i
.PHONY : source/Updates/UpdateInfoUsa.cpp.i

source/Updates/UpdateInfoUsa.s: source/Updates/UpdateInfoUsa.cpp.s

.PHONY : source/Updates/UpdateInfoUsa.s

# target to generate assembly for a file
source/Updates/UpdateInfoUsa.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateInfoUsa.cpp.s
.PHONY : source/Updates/UpdateInfoUsa.cpp.s

source/Updates/UpdateItem.obj: source/Updates/UpdateItem.cpp.obj

.PHONY : source/Updates/UpdateItem.obj

# target to build an object file
source/Updates/UpdateItem.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateItem.cpp.obj
.PHONY : source/Updates/UpdateItem.cpp.obj

source/Updates/UpdateItem.i: source/Updates/UpdateItem.cpp.i

.PHONY : source/Updates/UpdateItem.i

# target to preprocess a source file
source/Updates/UpdateItem.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateItem.cpp.i
.PHONY : source/Updates/UpdateItem.cpp.i

source/Updates/UpdateItem.s: source/Updates/UpdateItem.cpp.s

.PHONY : source/Updates/UpdateItem.s

# target to generate assembly for a file
source/Updates/UpdateItem.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Updates/UpdateItem.cpp.s
.PHONY : source/Updates/UpdateItem.cpp.s

source/Utility.obj: source/Utility.cpp.obj

.PHONY : source/Utility.obj

# target to build an object file
source/Utility.cpp.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Utility.cpp.obj
.PHONY : source/Utility.cpp.obj

source/Utility.i: source/Utility.cpp.i

.PHONY : source/Utility.i

# target to preprocess a source file
source/Utility.cpp.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Utility.cpp.i
.PHONY : source/Utility.cpp.i

source/Utility.s: source/Utility.cpp.s

.PHONY : source/Utility.s

# target to generate assembly for a file
source/Utility.cpp.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/Utility.cpp.s
.PHONY : source/Utility.cpp.s

source/libmd5-rfc/md5.obj: source/libmd5-rfc/md5.c.obj

.PHONY : source/libmd5-rfc/md5.obj

# target to build an object file
source/libmd5-rfc/md5.c.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/libmd5-rfc/md5.c.obj
.PHONY : source/libmd5-rfc/md5.c.obj

source/libmd5-rfc/md5.i: source/libmd5-rfc/md5.c.i

.PHONY : source/libmd5-rfc/md5.i

# target to preprocess a source file
source/libmd5-rfc/md5.c.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/libmd5-rfc/md5.c.i
.PHONY : source/libmd5-rfc/md5.c.i

source/libmd5-rfc/md5.s: source/libmd5-rfc/md5.c.s

.PHONY : source/libmd5-rfc/md5.s

# target to generate assembly for a file
source/libmd5-rfc/md5.c.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/libmd5-rfc/md5.c.s
.PHONY : source/libmd5-rfc/md5.c.s

source/svchax/svchax.obj: source/svchax/svchax.c.obj

.PHONY : source/svchax/svchax.obj

# target to build an object file
source/svchax/svchax.c.obj:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/svchax/svchax.c.obj
.PHONY : source/svchax/svchax.c.obj

source/svchax/svchax.i: source/svchax/svchax.c.i

.PHONY : source/svchax/svchax.i

# target to preprocess a source file
source/svchax/svchax.c.i:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/svchax/svchax.c.i
.PHONY : source/svchax/svchax.c.i

source/svchax/svchax.s: source/svchax/svchax.c.s

.PHONY : source/svchax/svchax.s

# target to generate assembly for a file
source/svchax/svchax.c.s:
	$(MAKE) -f CMakeFiles/PlaiSysUpdater.dir/build.make CMakeFiles/PlaiSysUpdater.dir/source/svchax/svchax.c.s
.PHONY : source/svchax/svchax.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PlaiSysUpdater"
	@echo "... PlaiSysUpdater_3dsx"
	@echo "... PlaiSysUpdater_Citra"
	@echo "... PlaiSysUpdater_3dslink"
	@echo "... PlaiSysUpdater_Cia"
	@echo "... source/Debug.obj"
	@echo "... source/Debug.i"
	@echo "... source/Debug.s"
	@echo "... source/Main.obj"
	@echo "... source/Main.i"
	@echo "... source/Main.s"
	@echo "... source/SuperUserLib3DS/libsu.obj"
	@echo "... source/SuperUserLib3DS/libsu.i"
	@echo "... source/SuperUserLib3DS/libsu.s"
	@echo "... source/Updates/UpdateInfoEur-2-1.obj"
	@echo "... source/Updates/UpdateInfoEur-2-1.i"
	@echo "... source/Updates/UpdateInfoEur-2-1.s"
	@echo "... source/Updates/UpdateInfoEur.obj"
	@echo "... source/Updates/UpdateInfoEur.i"
	@echo "... source/Updates/UpdateInfoEur.s"
	@echo "... source/Updates/UpdateInfoJpn-2-1.obj"
	@echo "... source/Updates/UpdateInfoJpn-2-1.i"
	@echo "... source/Updates/UpdateInfoJpn-2-1.s"
	@echo "... source/Updates/UpdateInfoJpn.obj"
	@echo "... source/Updates/UpdateInfoJpn.i"
	@echo "... source/Updates/UpdateInfoJpn.s"
	@echo "... source/Updates/UpdateInfoUsa-2-1.obj"
	@echo "... source/Updates/UpdateInfoUsa-2-1.i"
	@echo "... source/Updates/UpdateInfoUsa-2-1.s"
	@echo "... source/Updates/UpdateInfoUsa.obj"
	@echo "... source/Updates/UpdateInfoUsa.i"
	@echo "... source/Updates/UpdateInfoUsa.s"
	@echo "... source/Updates/UpdateItem.obj"
	@echo "... source/Updates/UpdateItem.i"
	@echo "... source/Updates/UpdateItem.s"
	@echo "... source/Utility.obj"
	@echo "... source/Utility.i"
	@echo "... source/Utility.s"
	@echo "... source/libmd5-rfc/md5.obj"
	@echo "... source/libmd5-rfc/md5.i"
	@echo "... source/libmd5-rfc/md5.s"
	@echo "... source/svchax/svchax.obj"
	@echo "... source/svchax/svchax.i"
	@echo "... source/svchax/svchax.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

